version: '3'

services:
  app:
    image: golang:stretch
    working_dir: /go/src/cvlv
    ports:
      - 32971:4000
    volumes:
      - .:/go/src/cvlv
    links:
      - redis
    env_file:
      - .env
    command: tail -f /dev/null

  redis:
    image: redis
    ports:
      - "6379:6379"
